##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [5]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr[[0,2,1]]

array([10, 30, 20])

You can do this fancy indexing in 2D Matrix aswell

In [11]:
matrix = np.arange(1,21).reshape(4,5)
print(matrix)
matrix[[3,2,0],[4,2,4]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([20, 13,  5])

##Conditional Selection
Find values based on conditions or replace them.

In [15]:
arr = np.arange(1,21)
np.where(arr %2==0,arr,0)

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [19]:
arr = np.array([1,2,1,4,2,4,7,5,4,7,5,8,58,58,5,854,85,8,658,32])
np.sort(arr)


array([ 0,  2,  1,  4,  3,  5,  8,  7, 14, 10,  6,  9, 11, 17, 19, 12, 13,
       16, 18, 15])

In [20]:
np.argsort(arr)

array([ 0,  2,  1,  4,  3,  5,  8,  7, 14, 10,  6,  9, 11, 17, 19, 12, 13,
       16, 18, 15])

##Concatenation & Stacking

In [21]:
a = np.array([1,2,3])
b=np.array([4,5,6])
np.concat([a,b])



array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [28]:
a = np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])