##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [9]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-2])

1
5


Now lets see the 2D indexing aswell

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(arr[0])

[1 2 3]


In [14]:
print(arr[0,1])
print(arr[2,1])
print(arr[1,2])

2
8
6


Now we can also do the slicing lets see the **slicing in 1D**

In [15]:
arr = np.array([1,2,3,4,5])
print(arr[1:4])


[2 3 4]


1D slicing was really easy now lets see the **slicing in 2D**

In [24]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(arr[1:,1:])
print(arr)
print(arr[0:,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


There is one more thing known as **Boolean indexing**

In [26]:
arr= np.array([1,2,3,4,5,6,7,8,8,9,0])
print(arr>3)
print(arr[arr>4])

[False False False  True  True  True  True  True  True  True False]
[5 6 7 8 8 9]


In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr > 3
arr[arr>5]

array([6, 7, 8, 9])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [39]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [46]:
arr = np.arange(1,31).reshape(6,5).flatten()
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
