# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
l = [ 1,2,3,4,5,6,7]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6, 7])

Lets create a matrix using list

In [5]:
l = [ [ 1,2,3],[4,5,6],[7,8,9]]
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [6]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [8]:
arr = np.zeros([6,6])
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones([6,6])
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
arr=np.full([5,5] , 7)
arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [12]:
arr = np.arange(1,11,2)
arr


array([1, 3, 5, 7, 9])

In [13]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(6,7)

array([[0.10414745, 0.38846723, 0.40949426, 0.21160058, 0.03785709,
        0.04951869, 0.74547778],
       [0.71752821, 0.82221784, 0.9491687 , 0.45247729, 0.0539709 ,
        0.31559463, 0.9449568 ],
       [0.69808482, 0.38065856, 0.36530445, 0.78508052, 0.73635051,
        0.57042499, 0.05180554],
       [0.09761014, 0.65781522, 0.67641046, 0.60193766, 0.75049078,
        0.73882201, 0.90678331],
       [0.26808261, 0.55387085, 0.71658867, 0.66011774, 0.24817186,
        0.78894558, 0.45868781],
       [0.78648803, 0.32547844, 0.3473939 , 0.02333372, 0.85999923,
        0.79157513, 0.37705249]])

In [16]:
np.random.randint(1,10,(3,3))

array([[3, 8, 1],
       [4, 8, 5],
       [6, 9, 1]])

In [17]:
arr = np.random.randn(2,4)
arr

array([[-1.01401889, -0.24365316,  0.74224435, -0.77270548],
       [ 1.3594799 , -0.18159619, -1.59903453, -0.51990985]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution

In [18]:
arr = np.arange(1,10,2)
arr


array([1, 3, 5, 7, 9])

In [20]:
from re import A
arr = np.linspace(1,20,5)
arr

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [25]:
arr = np.eye(10,3)
arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
arr = np.random.rand(1)
arr

array([0.62426131])

In [30]:
arr = np.random.randint(1,20,10)
arr

array([12, 17, 14,  8, 18, 15, 13,  4,  4,  5])

In [33]:
arr = np.random.randn(1,3)
arr

array([[ 0.12018647,  1.30585484, -1.44161508]])