##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [3]:
import numpy as np
b= np.array([1,2,3,4,5])
a= np.array([10,20,30,40,50])

print(a+b)
print(a//b)
print(a-b)
print(a*b)

[11 22 33 44 55]
[10 10 10 10 10]
[ 9 18 27 36 45]
[ 10  40  90 160 250]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [8]:
arr =np.array([ 1,2,3,4,5,6,7,8,9])
print(arr*2)

[[ 2  4  6  8 10 12 14 16 18]
 [ 2  4  6  8 10 12 14 16 18]]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [9]:
arr = np.array([[1,2,3,],[4,5,6]])

print(arr*2)

[[ 2  4  6]
 [ 8 10 12]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [11]:
arr = np.array([1,2,3,4,5,7,5,4,3,3,4,6,64,3,32,35,7,7,4])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))

199
10.473684210526315
15.557595609972477
242.03878116343486
64
1


You can also do the axis based operations row-Wise and Colum-wise

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=0))
print(np.mean(arr,axis=1))
print(np.mean(arr,axis=0))

[ 6 15 24]
[12 15 18]
[2. 5. 8.]
[4. 5. 6.]
